### ISSUE TITLE
[Enhancement] "Copy description and categories to all below"

### ISSUE THREAD

**Issue by nicolas-raoul** [yarl/vicuna#109]
Sometimes I upload a series of very similar pictures, for instance all stamps of a particular stamp series.
In that case, all images share a lot of common categories.
After filling metadata for the first image, clicking "Copy description and categories from above" for every single file is time-wasting.

So, how about a button (maybe in the menu) to paste description and categories to all images below? With a confirmation popup if judged necessary.

**Comment by Krzysiu** [comment]
You should choose files you want and apply whatever you want to selected files. Second icon from the right on the toolbar :)

**Comment by nicolas-raoul** [comment]
Thanks that's great indeed!
For future readers: Please note that selection has nothing to do with the checkbox.
