### ISSUE TITLE
permission = null

### ISSUE THREAD

**Issue by Aschroet** [yarl/vicuna#111]
On Commons i found more than 4k files that had "permission = null" and which were all uploaded by VicunaUploader. Example: https://commons.wikimedia.org/w/index.php?title=File:Pestmarterl_Ehenfeld-1065.jpg&oldid=184837134, resp. the uploads if this user: https://commons.wikimedia.org/w/index.php?title=Special:ListFiles/Ziegler175&ilshowall=1. For now I already cleaned the files. However, in my opinion the null should be avoid for all parameter of the information _template.

**Comment by michal-josef-spacek** [comment]
@Aschroet I believe, that i could close this issue. When field is blank, permission line is without value. When field is filled, value is on place.
