### ISSUE TITLE
Could you release 1.24? (change the version number in code)

### ISSUE THREAD

**Issue by Ciantic** [yarl/vicuna#114]
I've just found out you have fixed bugs since 1.23 was released, such as [longitude bug](https://commons.wikimedia.org/wiki/Commons_talk:Vicu%C3%B1aUploader#Geotag_bug.3F). However, getting that bug fix required recompiling from the source code.

Could you change the version number in the source code and release new version?

I know maintaining this is not your highest priority in life, but it's a bit confusing at the moment. Thanks.

**Comment by yarl** [comment]
Yeah, as you probably see, it's not. Sorry for that. I will try to catch up and do the release next week or so. We will see how it goes.
