### ISSUE TITLE
Problem with fonts in high resolution display

### ISSUE THREAD

**Issue by olea** [yarl/vicuna#117]
Hi:

Using Vicuña 1.23 in a Linux system with a 1920x1080 resolution. I use a default 12 font size + 1.25 magnification.

When launching Vicuña windows content get messed, probably related with system fonts sizes. I tried several runtimes with similar output:

java-1 8 0-oracle-1 8 0 181:

![vicuna-java-1 8 0-oracle-1 8 0 181](https://user-images.githubusercontent.com/141267/48890977-8e6fb700-ee3a-11e8-9774-983e99175daf.png)

openjdk-1 8 0 191 b12: 
![vicuna-penjdk-1 8 0 191 b12](https://user-images.githubusercontent.com/141267/48890978-8e6fb700-ee3a-11e8-97f4-a09b2534170c.png)

openjdk-11 0 1 13:
![vicuna-openjdk-11 0 1 13](https://user-images.githubusercontent.com/141267/48890979-8e6fb700-ee3a-11e8-80eb-a57ac078f047.png)

As far as I know it's a Java problem. But I can't figure out how to set Vicuña or Java font sizes for correct visualization.

**Comment by michal-josef-spacek** [comment]
@olea Could you test 1.24-beta2 ? I am using in this resolution and it's fine. Debian openjdk 11.0.11

**Comment by olea** [comment]
> @olea Could you test 1.24-beta2 ? I am using in this resolution and it's fine. Debian openjdk 11.0.11

Oh. Now it works, Thank you.

The only thing I miss is to change the application font size :-)
