### ISSUE TITLE
Cannot log into VicuñaUploader 1.23

### ISSUE THREAD

**Issue by Mistr81** [yarl/vicuna#118]
On Windows 7 Home Premium, I can not log into VicuñaUploader 1.23. My login is "Jan Polák". Where is the problem? Thank you.

**Comment by Mistr81** [comment]
Now it's OK, It was necessary to change the password. Existing was too short.

**Comment by Mistr81** [comment]
Now it's OK, It was necessary to change the password. Existing was too short.

**Comment by FlominatorTM** [comment]
Friend of mine had the same problem. Looks like at least the Wikimedia wikis meanwhile require eight characters. I don't know if there is a way to retrieve $wgMinimalPasswordLength via API or if it would be an idea to show a more precise error message when trying to log in with a shorter password? Else people might search forever ...
