### ISSUE TITLE
Minor improvement

### ISSUE THREAD

**Issue by Aschroet** [yarl/vicuna#119]
Right clicking in the description field allows to add language templates in three languages. However, these templates should use a numbered parameter to avoid possible rendering problems, i. e. instead of "{{en|" it should have "{{en|1=".
I guess this can be changed in:

_Settings.java:_
 quickTemplates.add(new QuickTemplate(Data.text("file-wiki-en"), "{{en|%TEXT%}}", true));
...

**Comment by michal-josef-spacek** [comment]
@Aschroet I improved this in #147
