### ISSUE TITLE
Not loading GPS coordinates

### ISSUE THREAD

**Issue by Mistr81** [yarl/vicuna#121]
I have VicunaUploader 1.23.

When I describe photos, I add GPS coordinates to them. If I save the project, it also contains the coordinates you have entered. If I have the project reloaded, the coordinates will no longer be loaded. Please fix this problem. Thank you.

**Comment by dominikmatus** [comment]
In my case it does not even save the coordinates to the XML fine

**Comment by michal-josef-spacek** [comment]
@Mistr81  VicunaUploader 1.23 isn't supported now. In last version (development) is this issue fixed.

**Comment by CodingLama** [comment]
> @Mistr81 VicunaUploader 1.23 isn't supported now. In last version (development) is this issue fixed.

What is the last version of development? In 1.24 I even cannot open the session after adding coordinates in it.

**Comment by michal-josef-spacek** [comment]
@CodingLama https://github.com/yarl/vicuna/tags
Could you describe issue better?

**Comment by CodingLama** [comment]
> @CodingLama https://github.com/yarl/vicuna/tags
> Could you describe issue better?

I guess it is in Google Sheets, which you have access to. What I am doing here is to reproduce #121 to see, which steps leads to this problem.

**Comment by michal-josef-spacek** [comment]
@CodingLama In Google Sheets is nothing related to this. I tested and fixed this issue. So when is something similar in 1.24-beta4, i need to understand what happened.
