### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by berrely** [yarl/vicuna#126]
There seem to be many issues and a few PRs, and the last release was in 2016. Has this been abandoned?

**Comment by michal-josef-spacek** [comment]
No really. Some guys want to support. I created #125 with some fixes. We can release new version and talk about important things.

**Comment by berrely** [comment]
I understand there is still an active community for it, but the maintainers seem to have ignored it. Maybe a current maintainer can make some active contributors maintainers to merge some PRs.

**Comment by michal-josef-spacek** [comment]
@berrely I have merge rights. Still i need help from users.

**Comment by michal-josef-spacek** [comment]
@berrely What's main problem of vicuna now?

**Comment by michal-josef-spacek** [comment]
FYI: https://meta.m.wikimedia.org/wiki/Grants:Project/Rapid/Juandev/Accessibility_and_improvement_of_Vicu%C3%B1aUploader

**Comment by berrely** [comment]
> 
> 
> @berrely What's main problem of vicuna now?

Non really. There's nothing wrong with a project not having updated for a while, but there are some features that Vicuna lacks, such as not even appending templates such as {{[VicuñaUploader](https://commons.wikimedia.org/wiki/Template:Vicu%C3%B1aUploader)}} or similar automatically. I guess I'll close this issue. This is a great tool, much better than Commonist and other similar tools. I hope this Grant is successful!

**Comment by michal-josef-spacek** [comment]
@berrely I added https://github.com/yarl/vicuna/issues/127

**Comment by saper** [comment]
@michal-josef-spacek big big thanks for taking this project over!
