### ISSUE TITLE
Enable providing different external descriptions for uploaded files

### ISSUE THREAD

**Issue by twkozlowski** [yarl/vicuna#13]
It would be handy to be able to provide different external descriptions for multiple files uploaded at once; this would help a lot with batch uploading, when file descriptions are very similar to each other, and are only changed with command line text processing tools (sed, grep, awk, etc.).

**Comment by yarl** [comment]
[Old tickets cleaning]

I think for now [custom description mechanism](https://github.com/yarl/vicuna/wiki/Custom-description) is enough for fancy upload.
