### ISSUE TITLE
Bug - Save session-File - coord

### ISSUE THREAD

**Issue by osmvermesser** [yarl/vicuna#132]
hi!

when save session-file the lat/lon-value will be the same!

_<sessionFile>
      <date>2021-03-31</date>
      <path>F:\Wikipedia\2021\20210331\HL_Grenzsteinpark_1010.jpg</path>
      <cats>Grenzsteinpark</cats>
      <name>HL_Grenzsteinpark_1010</name>
      <coor>
        <latitude>53.836566</latitude>
        <longitude>53.836566</longitude>
      </coor>
      <desc>Historischer Grenzstein der Hansestadt Lübeck im Grenzsteinpark auf dem Uni-Gelände</desc>
    </sessionFile>_

regards Jan

**Comment by michal-josef-spacek** [comment]
Dev release with fix: https://skim.cz/tmp/vicuna-1.24-a627f3.zip
