### ISSUE TITLE
Vicuña can't check for updates

### ISSUE THREAD

**Issue by berrely** [yarl/vicuna#153]
Even though I have internet, Vicuña fails to start and throws this error:
```
C:\Users\[REDACTED]\Desktop\Portable Programs\vicuna-1.23>java -jar vicuna.jar
Jul 07, 2021 6:53:15 PM Wiki namespace
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?maxlag=5&format=xml&action=query&meta=siteinfo&siprop=namespaces
Jul 07, 2021 6:53:16 PM Wiki namespace
INFO: [commons.wikimedia.org] Successfully retrieved namespace list (41 namespaces)
Jul 07, 2021 6:53:16 PM Wiki getPageText
INFO: Fetching URL https://commons.wikimedia.org/w/index.php?maxlag=5&title=User%3AYarl%2FVicunaUploader%2Fversion&action=raw
Jul 07, 2021 6:53:16 PM cuploader.frames.FIntro error
SEVERE: Cannot check for the new version
```
Any ideas? Windows 10 64 bit with the latest release.

**Comment by michal-josef-spacek** [comment]
@berrely which version? In each time i need to know exact version.

**Comment by berrely** [comment]
Vicuña Uploader 1.23, Java 8 Update 291, Windows build 21H2. Strangely it was working a few minutes ago.

**Comment by michal-josef-spacek** [comment]
@berrely could you try 1.24-beta2? 1.23 is obsolete. Probably must upgrade java to 11 version.

**Comment by berrely** [comment]
Sure, can I copy my settings file over?

**Comment by michal-josef-spacek** [comment]
@berrely that's good question. I don't know. I created some upgrades of config file. The best way is backup and fill new one with old values after saving new one.

**Comment by berrely** [comment]
It's fine, I picked up anyways. Seems to be working, and quite a few new features! Didn't know there were beta releases. Thanks :D

**Comment by michal-josef-spacek** [comment]
@berrely could you send me conf file to michal.josef.spacek@gmail.com? I will look to changes

**Comment by michal-josef-spacek** [comment]
@berrely i released beta2 yesterday. I will release beta3 nearly. Still i need some testers. I haven't windows in this time.
