### ISSUE TITLE
action=query&prop=info&intoken API calls

### ISSUE THREAD

**Issue by reedy** [yarl/vicuna#154]
In support of https://phabricator.wikimedia.org/T280806, it seems VicunaUploader/1.23 (at least) is still doing `action=query&prop=info&intoken` API calls.

I can't see if this has been fixed in the many commits since 1.23 in https://github.com/yarl/vicuna/compare/1.23...master but if it's not... can someone please fix it?

And if it is fixed... Any chance we can get a release to stop these calls happening by people upgrading?

Thanks!

**Comment by michal-josef-spacek** [comment]
@reedy Could you check 1.24-beta2?

**Comment by reedy** [comment]
I'm guessing this may have been fixed due to some update of the https://github.com/MER-C/wiki-java inside vicuna...

Based on https://github.com/MER-C/wiki-java/blob/05aae5a87498c187c533909eb448b7923e70f011/src/org/wikipedia/Wiki.java#L1486-L1502 added in https://github.com/MER-C/wiki-java/commit/9dc236e644cc1dc6ddd33ec964a9f018f207af9a

Based on https://github.com/yarl/vicuna/blob/1.23/src/org/wikipedia/Wiki.java which used `intoken`

When 1.24 goes stable and people update, that should mostly fix up the issue

**Comment by michal-josef-spacek** [comment]
@reedy Yes, i updated Wiki.java to some version, still i cannot update to last version, because some issue :-/

Last pre-release is: https://github.com/yarl/vicuna/releases/tag/1.24-beta2 we need to check.
When i am looking to code, this intoken isn't here. So i am closing ticket. Thanks :-)
