### ISSUE TITLE
Enable overwriting existing files

### ISSUE THREAD

**Issue by ghost** [yarl/vicuna#17]
It should be possible to overwrite existing files; the current behaviour is to warn the user that the filename already exists and to stop the upload. 

The user should be able to overwrite existing files after confirming that s/he knows what s/he's doing.

**Comment by albore** [comment]
I am testing version 1.23 and there is no possibility to overwrite a file with a new version. Vicuna simply adds the new upload to the gallery (if the option is set), but without uploading anything.
