### ISSUE TITLE
V 1.16 wrong file name check

### ISSUE THREAD

**Issue by CodingLama** [yarl/vicuna#18]
I got wrong file name check:
*Zásmuky, věž zámku.jpg - file must have a unique name
*Zásmuky, mariánský sloup, svatý (001).jpg - same

these files doesnt exist on Commons.

**Comment by michal-josef-spacek** [comment]
@CodingLama 1.16 isn't supported. On last 1.24-beta3 is this working, i believe.

**Comment by CodingLama** [comment]
What does it mean 1.16 isnt supported?

**Comment by michal-josef-spacek** [comment]
@CodingLama There is new version and I don't want to talk about old versions, which had weird issues.
