### ISSUE TITLE
Option for disable Description tag. 

### ISSUE THREAD

**Issue by dominikmatus** [yarl/vicuna#21]
Is it possible to add option for disabling =={{int:filedesc}}== and {{Information}} tag? I'm ofter uploading with Artwork tag and this is a problem. I had to delete it manualy.

See here: http://commons.wikimedia.org/w/index.php?title=File:Backgammon_board_in_Moravian_Gallery_(02).jpg&diff=92481009&oldid=92479259

**Comment by yarl** [comment]
This is [already done](https://commons.wikimedia.org/wiki/Commons_talk:Vicu%C3%B1aUploader/Archive_1#Suggested_feature), but needs proper documentation.

**Comment by yarl** [comment]
Done, see [article on wiki](https://github.com/yarl/vicuna/wiki/Custom-description).
