### ISSUE TITLE
No recent build on http://yarl.github.io/vicuna/

### ISSUE THREAD

**Issue by siebrand** [yarl/vicuna#32]
There is no recent build on http://yarl.github.io/vicuna/. This also means that the latest localisation are not being made available to potential users.

**Comment by yarl** [comment]
I'm finally back info vicuna after long time, updates should be regular now.

**Comment by saper** [comment]
Ok, but now `dist` directory is versioned by git and during development `vicuna.jar` gets overwritten every time... What about using [GitHub release binary feature](https://github.com/blog/1547-release-your-software) to post read-to-use .zips?
