### ISSUE TITLE
Ant build does not result in the same jar as distributed

### ISSUE THREAD

**Issue by nicolas-raoul** [yarl/vicuna#34]
1. Download latest vicuna source code
2. Run `ant jar`
3. Run `java -jar dist/vicuna.jar`
4. Result: Crash `Exception in thread "main" java.lang.NoClassDefFoundError: com/thoughtworks/xstream/io/HierarchicalStreamDriver`

Running `java -jar /tmp/vicuna.jar` (downloaded from http://yarl.github.io/vicuna/) works.

The vicuna.jar built from source code contains much less classes than the distributed one.

Running `java -cp lib/xstream-1.4.3.jar:lib/jmapviewer.jar:lib/metadata-extractor-2.6.0.jar:lib/xmpcore.jar -jar dist/vicuna.jar` does not work either.

In any case, a start script would be welcome in the source version too.

**Comment by yarl** [comment]
I've [added information](https://github.com/yarl/vicuna/blob/master/README.md#building) about custom build target. Sorry for big delay on this.
