### ISSUE TITLE
CC-BY-SA-4.0 licence

### ISSUE THREAD

**Issue by xkomczax** [yarl/vicuna#36]
Is it possible to add CC-BY-SA-4.0 licence to the default list? Or let users to specify author when using CC-BY-SA-4.0 (this option is not editable and usable when "other" licence is selected)?

**Comment by yarl** [comment]
You can always write `{{cc-by-sa-4.0|Author Name}}`, that's basically how author field works. But still, 4.0 licenses needs to be edded.

**Comment by xkomczax** [comment]
Thanks for comment. 

The issue is that once I am using "Other" licence field, the "Attribution" field is not usable (e.g. I want to use {{User:my-commons-nickname/author}}, not just simply my name)

**Comment by yarl** [comment]
OK, so you are talking about `|author = [[user:...|...]]` in `{{Information}}` template?

**Comment by xkomczax** [comment]
Exactly! :-) An example can be found here: https://commons.wikimedia.org/wiki/File:Star%C3%A1_Amat%C3%A9rsk%C3%A1_jeskyn%C4%9B_-_B%C3%ADl%C3%A1_voda_v_Povod%C5%88ov%C3%A9_chodb%C4%9B.jpg

**Comment by yarl** [comment]
OK, to this is the other issue. You can use [custom description](https://github.com/yarl/vicuna/wiki/Custom-description) to do this.

**Comment by xkomczax** [comment]
Oh, OK, I thought the Author field can be changed in GUI through "Attribution" field (e.g. by writing here {{User:Xkomczax/author}} ) , because this option works in Commonist, Vicunas ascendant  (and that there is some interconnection with licence as it lies right down of it).

**Comment by xkomczax** [comment]
Now I tried to change the settings and when I choose "Other" licence, the "Attribution" field is undietable. By choosing some other, for example CC-BY-SA 3.0 licence I can edit the "Attribution" field (two screenshots are attached)
![cc-by-sa-3 0](https://cloud.githubusercontent.com/assets/3698242/6919102/76435e7a-d7b4-11e4-90f0-47fc45bd2e68.png)
![other](https://cloud.githubusercontent.com/assets/3698242/6919103/76514878-d7b4-11e4-9170-4b053ab52933.png)

**Comment by saper** [comment]
Implementation note: in the settings we store just the ID of the license (number on the list).
This needs to be more meaningful (future-proof). Otherwise after upgrade user's choice may be silently changed: in 1.21 "0" is CC-BY-SA 3.0, if we add CC-BY-SA 4.0 as the first choice it will be the default for all CC-BY-SA 3.0 users!

**Comment by yarl** [comment]
Yes, it needs breaking change.

**Comment by saper** [comment]
I have an idea how to fix this in a relatively non-intrusive way. What do you think about introducing some simple versioning of the session.xml/settings.xml format?
