### ISSUE TITLE
Option to disable getCurrentDatabaseLag check?

### ISSUE THREAD

**Issue by nicolas-raoul** [yarl/vicuna#40]
Thanks for this great software!

I use it over a costly mobile connection. It usually takes me days to categorize all of my pictures (a bit every evening).
I noticed that Vicuna sends [requests](https://commons.wikimedia.org/w/api.php?maxlag=5&format=xml&action=query&meta=siteinfo&siprop=dbrepllag) all day long, even before I log in.  
It makes me worry for my mobile connection, and for the Wikimedia resources.

```
INFO: [commons.wikimedia.org] Current database replication lag is 0 seconds
Apr 30, 2015 5:25:59 PM Wiki getCurrentDatabaseLag
INFO: Fetching URL https://commons.wikimedia.org/w/api.php?maxlag=5&format=xml&action=query&meta=siteinfo&siprop=dbrepllag
```

Is there any way to disable this ping?
Thanks!

**Comment by yarl** [comment]
Yes, good point.

**Comment by saper** [comment]
I have implemented this feature in https://github.com/yarl/vicuna/pull/41. Feel free to test!

**Comment by nicolas-raoul** [comment]
Wonderful, thanks! :-D
