### ISSUE TITLE
Replace JMapViewer in FAbout.form with jxmapviewer2

### ISSUE THREAD

**Issue by eldur** [yarl/vicuna#58]
... sorry I've not installed your IDE to fix this

**Comment by saper** [comment]
IDE is not required, 
I am using vi.

**Comment by eldur** [comment]
okay I assumed the the *.form files are transformed by netbeans to java files.

I'll offer to send a pull request first, that deletes all redundant *.form files first - okay?

**Comment by saper** [comment]
Well, no - .form files are needed for round-tripping with Matisse, NetBeans form editor. I've never had trouble editing them by hand. In the respective .java files generated sections are marked with comments. This limits us in some ways, but let's keep it as long as it's feasible.
