### ISSUE TITLE
Vicuña freezes when selecting a folder

### ISSUE THREAD

**Issue by nicolas-raoul** [yarl/vicuna#77]
1. Launch VicuñaUploader from Ubuntu 2015.10
2. Click "Read files"
3. Click on anything in the "Folders" area of the dialog that appears
4. Freeze. Nothing reacts to clicks/keyboard. The only solution is to kill Vicuña.

This makes the program unusable. Nothing in the log:

```
INFO: Fetching URL https://commons.wikimedia.org/w/index.php?maxlag=5&title=User%3AYarl%2FVicunaUploader%2Fversion&action=raw
May 16, 2016 7:39:40 PM Wiki getPageText
INFO: [commons.wikimedia.org] Successfully retrieved text of User:Yarl/VicunaUploader/version
```

Reproduced with Vicuña 1.20 and 1.23

**Comment by nicolas-raoul** [comment]
Same freeze with the "Files" component of the "open session" dialog.
Workaround: type the name of the session file instead of clicking it.

**Comment by michal-josef-spacek** [comment]
@nicolas-raoul Could you test this with 1.24-beta4? (https://github.com/yarl/vicuna/releases/tag/1.24-beta4)

**Comment by nicolas-raoul** [comment]
Sorry I unfortunately can't test anymore, but thanks for taking care of this! 🙂

**Comment by michal-josef-spacek** [comment]
I will close this ticket. Similar thing is in https://github.com/yarl/vicuna/issues/105
