### ISSUE TITLE
Pictures listed in seemingly random order

### ISSUE THREAD

**Issue by nicolas-raoul** [yarl/vicuna#79]
When I load a directory of pictures, the files are not loaded in alphanumerical order, nor in modification date order, but seemingly in a random order:
![vicuna-order](https://cloud.githubusercontent.com/assets/99590/15288197/b4436b0a-1ba3-11e6-959d-2041f2ee01db.png)

As you can see, the order is random:

`DSCF9338.JPG DSCF9280.JPG DSCF9263.JPG DSCF9281.JPG DSCF9333.JPG`

It prevents me from copying description and categories from above/below efficiently, as two subsequent pictures can be a hundred rows apart.
Ubuntu 2015.10, Vicuña compiled from latest Git 83e8772dc7ef7916349812b65f59a421cab7ecfa

**Comment by michal-josef-spacek** [comment]
Fixed in #159
