### ISSUE TITLE
Minor "dirt" in description

### ISSUE THREAD

**Issue by CodingLama** [yarl/vicuna#8]
Hi another minor problem. There is something which looks like the dubble dot uppon German letters. I attach screenshot. Now in the moment it is upon "R", and as I type it disapears or move upon text.

Err how to attach file?

**Comment by saper** [comment]
Can you check again if this problem persists? It looks to me as a problem in the underlying graphical interface, not sure we can fix thus. Which operating system/windowing system is this?

**Comment by yarl** [comment]
This is probably unfixable for us.
