### ISSUE TITLE
Default directory setting not usable (because of HDPI?)

### ISSUE THREAD

**Issue by nicolas-raoul** [yarl/vicuna#80]
Settings > Program > Loading > Default directory

![vicuna-settings](https://cloud.githubusercontent.com/assets/99590/15288336/f02d65d4-1ba4-11e6-82e9-440e5e8c4c28.png)

Ubuntu 2015.10 with HDPI screen, Vicuña compiled from latest Git 83e8772dc7ef7916349812b65f59a421cab7ecfa

**Comment by CodingLama** [comment]
Does this problem persists, or we can close it as fixed?

**Comment by nicolas-raoul** [comment]
I have switched OS so I can't try anymore, unfortunately.

**Comment by CodingLama** [comment]
So I guess you hade Linux or something like that before?_

**Comment by nicolas-raoul** [comment]
Yes, I had Ubuntu Linux.
I guess this can be closed if nobody on Linux can reproduce the problem.

**Comment by CodingLama** [comment]
> Yes, I had Ubuntu Linux.
> I guess this can be closed if nobody on Linux can reproduce the problem.

Yes, probably it could be closed. I am running 1.24 on Ubuntu and it works.
