### ISSUE TITLE
Session does not save "select/deselect file to upload" information

### ISSUE THREAD

**Issue by nicolas-raoul** [yarl/vicuna#84]
1. Open a hundred pictures
2. Select which ones to upload
3. Let's say you need to switch off the computer because battery dies, so save to session
4. Open saved session
5. PROBLEM: The hundred pictures are all unselected for upload. Need to select again.

**Comment by michal-josef-spacek** [comment]
In session.xml isn't information about selecting.

**Comment by michal-josef-spacek** [comment]
Fixed in #161
