### ISSUE TITLE
OpenJDK 9.0 fails to launch vicuna.jar

### ISSUE THREAD

**Issue by mathieumd** [yarl/vicuna#85]
When trying to start Vicuna with OpenJDK, only the version 8 (8u91-b14-2) works. The version 9 (9~b80-2) fails with this message:

```bash
/usr/lib/jvm/java-9-openjdk-amd64/bin/java -jar vicuna.jar
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fae0a652399, pid=13315, tid=0x000000000000342d
#
# JRE version: OpenJDK Runtime Environment (9.0_02-b80) (build 1.9.0_02-internal-b80)
# Java VM: OpenJDK 64-Bit Server VM (1.9.0_02-internal-b80, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libjava.so+0x1f399]  JNU_GetEnv+0x19
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/mathieu/Downloads/hs_err_pid13315.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Abandon
```

PS: "Abandon" means "Abort" in French

**Comment by saper** [comment]
Can you publish hs_err.log?

**Comment by mathieumd** [comment]
[hs_err_pid1239.log.txt](https://github.com/yarl/vicuna/files/273434/hs_err_pid1239.log.txt)

**Comment by saper** [comment]
It looks like that your freetype library has some serious trouble reading one of the font files. This is probably not related to Vicuña or even Java. Maybe JDK9 does something a bit different there that leads to such a failure. You may try upgrading your freetype library first.

**Comment by mathieumd** [comment]
Do you have any suggestion to upgrade my freetype libary? My `libfreetype6` packages are the latests [offered by Debian Testing](https://packages.debian.org/stretch/libfreetype6): `2.6.3-3+b1`.
I also tried to install the package `libisfreetype-java`, but it didn't help.

**Comment by saper** [comment]
@mathieumd I'd suggested to open the issue with the Debian maintainers. Make sure to include the debug output you have posted here.

**Comment by mathieumd** [comment]
I got `openjdk-9-jre` it installed before using only Testing packages, and it was [from experimental](https://packages.debian.org/experimental/openjdk-9-jre), so nothing to worry about here. Sorry for the trouble!
