### ISSUE TITLE
Opening folders doesn't work, drag and drop does

### ISSUE THREAD

**Issue by FlominatorTM** [yarl/vicuna#97]
When I try to open a folder or a picture with the browse dialog I get this exception:

![awt queue](https://cloud.githubusercontent.com/assets/12448283/21752957/582819ca-d5e2-11e6-9de8-4dc96113e281.png)

Environment is XP and JRE 1.7.1_71 (so I'm prepared for "your platform is not supported" :) )

Except that the tools very powerful and or sure even more helpful then Commonist

**Comment by michal-josef-spacek** [comment]
Duplicate with #105, fixed in 1.24-beta3
