### ISSUE TITLE
use [Iptc] Caption/Abstract to populate description

### ISSUE THREAD

**Issue by FlominatorTM** [yarl/vicuna#98]
There is Iptc field "Caption/Abstract" in which some people put in descriptions of their pictures. It would be pretty cool, if Vicuna would be able to (optionally?) use this data in the description field.

**Comment by FlominatorTM** [comment]
After looking at the format Vicuna saves a session with, it might also be a workaround to create a small separate tool that maps existing files to entries in the session.xml and inserts the description by manually reading Iptc data. 

But before I start developing such thing, I would like to know, how are the changes of you integrating your own solution in Vicuna?

**Comment by FlominatorTM** [comment]
I couldn't help myself: https://github.com/FlominatorTM/iptc_to_vicuna

**Comment by yarl** [comment]
Great. Sorry for no response, there is big stagnation from my end on this project...

**Comment by FlominatorTM** [comment]
Pull request available on https://github.com/yarl/vicuna/pull/102

**Comment by michal-josef-spacek** [comment]
Applied in #157
